TASK-3: OOP-principles.
DimaLayeuski/AQA_Lab-1 pull request #5
Opened 2022-02-16 20:06 UTC by DimaLayeuski

NO-TASK: Added gitignore

2022-02-23 13:07 UTC, DaryaNikitina commented
Remove obj, bin and .idea directories. Add sln file.

2022-02-23 13:15 UTC, DimaLayeuski commented
> Remove obj, bin and .idea directories. Add sln file.

I have a problem with file from solution. I try to fix that today.

2022-03-04 16:59 UTC, DaryaNikitina requested changes

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Program.cs
> +var vehicles = vehicleGenerator.GenerateVehicles();
If you need to generate drivers and vehicles count as 2,5,10, you will go inside DriverGenerator and VehicleGenerator - modify count variable.
Create a variable and pass count through constructor here or better to pass in Generate methods.

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Program.cs
> +var choice = Console.ReadLine();
Make a check for incorrect input. If its incorrect - ask user to choose driver again

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Program.cs
> +                var time = mileage / vehicle.Engine.MaximumSpeed;
time is 0 every run

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Program.cs
> +}
We have only one attempt to see information. Make it in loop, where we can back and choose another option for information.

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Vehicle.cs
> +    public Engine Engine { get; set; }
Make all fields private.

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Truck.cs
> +    public bool HasPricep { get; set; }
Make a field private.

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/SportCar.cs
> +    private static bool HasExperience(Driver? person)
For private method, which you are calling inside the class - dont use static.

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Person.cs
> +    public bool IsDriver { get; set; } = default!;
Make all fields private. Remove = default!

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Minivan.cs
> +    public int SeatsCount;
Make a field private.

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Engine.cs
> +    public double AverageConsumption { get; set; } = default!;
Make all fields private. Remove = default!

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/DriverGenerator.cs
> +
Remove spaces(Empty lines)

2022-03-04 16:59 UTC, DaryaNikitina commented on AQA_Lab_Task/Driver.cs
> +    public Vehicle Vehicle { get; set; } = null!;
Make all fields private. Remove = default!
Remove unused field

2022-03-23 09:40 UTC, closed without merging